[package]
name = "thenotary/wasix-hello"
version = "0.1.3"
description = "This repo is a POC for validating changes to wasix-org/libc used to target wasix for rust builds"
readme = "./README.md"
entrypoint = "hello-wasix"

[[module]]
name = "hello-wasix"
source = "target/wasm32-wasmer-wasi/release/app.wasm"

[[command]]
name = "hello-wasix"
module = "hello-wasix"
runner = "https://webc.org/runner/wasi"
